name: Subnet calculator
version: "1.0"
about: A basic subnet calculator
author: Léo Huteau <huteau890@gmail.com>


args:
  - address:
      help: Must be a valid IP Address
      index: 1
      required: true
      takes_value: true

  - netmask:
      help: Mask must be in in CIDR format for all or classical format for IPv4
      index: 2
      required: true
      takes_value: true

  - subnetmask:
      help: Subnet mask must be in in CIDR format for all or classical format for IPv4
      index: 3
      required: true
      takes_value: true

  - csv:
      help: export data as CSV file
      short: c
      long: csv
      takes_value: true
      value_name: FILE

  - limit:
      help: Limit of showed subnetwork
      short: l
      long: limit
      possible_values: ["2", "4", "8", "16", "32", "64", "128"]
      takes_value: true
      value_name: LIMIT
