on:
  push:
    branches: [ master ]

name: Create Release

env:
  # Could, potentially automatically parse
  # the bin name, but let's do it automatically for now.
  RELEASE_BIN: subnet-calculator



jobs:
  build:
    name: Build release

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, windows]
        include:
          - build: linux
            os: ubuntu-latest
            rust: stable
          - build: windows
            os: windows-latest
            rust: stable

    steps:
      - uses: actions/checkout@v1

      - name: Install Rust (rustup)
        run: rustup update ${{ matrix.rust }} --no-self-update && rustup default ${{ matrix.rust }}
        shell: bash

      - name: Build
        run: cargo build --verbose --release

      - name: Create artifact directory
        run: mkdir artifacts

      - name: Copy for Linux
        run: cp ./target/release/${{ env.RELEASE_BIN }} ./artifacts/${{ env.RELEASE_BIN }}
        if: matrix.os == 'ubuntu-latest'

      - name: Copy for Windows
        run: cp ./target/release/${{ env.RELEASE_BIN }}.exe  ./artifacts/${{ env.RELEASE_BIN }}.exe
        if: matrix.os == 'windows-latest'


      # This will double-zip
      # See - https://github.com/actions/upload-artifact/issues/39
      - uses: actions/upload-artifact@v1
        name: Upload archive
        with:
          name: ${{ runner.os }}
          path: artifacts/
   
   

    
