name: Rust

on: [push, pull_request]

jobs:
  build-linux-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache release
        uses: actions/cache@v1
        env:
          cache-name: cache-rust
        with:
          path: target/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build
        run: cargo build --release --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Save artifact
        uses: actions/upload-artifact@v1
        with:
          name: yarrt-nightly
          path: target/release/rust_tracing